apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: miliariadnane/customer:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
