apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer # has to match .metadata.labels.app && template.metadata.labels.app of deployment || stafulset
  ports:
    - port: 80
      targetPort: 8001 # has to match containerPort of deployment || stafulset
  type: LoadBalancer
