apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: orders
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: http
      path: '/order/actuator/prometheus'
  selector:
    matchLabels:
      app: orders
