apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: customer
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: http
      path: '/customer/actuator/prometheus'
  selector:
    matchLabels:
      app: customer