#Spring
server:
  port: 8003
  error:
    include-message: always
#Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: miliariadnane
    password: password
  zipkin:
    baseUrl: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  profiles:
    active: kube
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
