apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: payment
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: http
      path: '/payment/actuator/prometheus'
  selector:
    matchLabels:
      app: payment