#Server
server:
  port: 8088
#Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
              - Path=/api/v1/customers/**
        - id: product
          uri: lb://PRODUCT
          predicates:
              - Path=/api/v1/products/**
        - id: order
          uri: lb://ORDER
          predicates:
              - Path=/api/v1/orders/**
        - id: payment
          uri: lb://PAYMENT
          predicates:
              - Path=/api/v1/payments/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
              - Path=/api/v1/notifications/**
  profiles:
    active: docker
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
