#Server
server:
  port: 8765
#Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER # lb = load balancer
          predicates:
            - Path=/api/v1/customers/**, /v3/api-docs/customer
        - id: product
          uri: lb://PRODUCT
          predicates:
              - Path=/api/v1/products/**, /v3/api-docs/product
        - id: order
          uri: lb://ORDER
          predicates:
              - Path=/api/v1/orders/**, /v3/api-docs/order
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payments/**, /v3/api-docs/payment
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
              - Path=/api/v1/notifications/**, /v3/api-docs/notification
        - id: apiKey-manager
          uri: lb://APIKEY-MANAGER
          predicates:
              - Path=/api/v1/apiKey-manager/api-keys/**, /api/v1/apiKey-manager/applications/**, /v3/api-docs/**
  profiles:
    active: default

#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
