apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification # has to match .metadata.labels.app && template.metadata.labels.app of deployment || stafulset
  ports:
    - port: 80
      targetPort: 8004 # has to match containerPort of deployment || stafulset
  type: ClusterIP
