apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: orders
          image: miliariadnane/product:12.09.2022.17.36.48
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: eks
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dbsecretd
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: db_password
      restartPolicy: Always
